### ISSUE TITLE
Executor gets "stuck" with a RuntimeError

### ISSUE THREAD

**Issue by justin1364** [dchevell/flask-executor#34]
First, this is an insanely useful repo –– thanks!

Everything is working great in my code except for a weird situation in which my Flask app tries to do this:

```
@app.route("/do_work")
def do_work_route():
    executor.submit(
        my_function,
       my_argument)

    return "Doing work.", 200
```

And sometimes this results in:

```
  File "/Users/justin/venv/rloo/lib/python3.7/site-packages/flask_executor/executor.py", line 162, in submit
    future = self._self.submit(fn, *args, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 153, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```

Which is persistent until I restart the app completely. Locally I can repro the issue by hitting the `do_work_route()`, changing code which auto-reloads before `my_function()` completes, and then I get the persistent RuntimeError.

However, on my production machine, which is running gunicorn, I'm seeing the same persistent error, and I'm not sure how it started.

I'm not sure if this is helpful, but `my_function()` is running long-running Postgres queries with psycopg2.

**Comment by dchevell** [comment]
Going through old issues, your local repro case isn't surprising since you're effectively tearing down the app and restarting it, which unsurprisingly shuts down the executor - I'd consider that expected behaviour.

The gunicorn one is something else, that sounds like it would be a valid issue. Unfortunately I can't reproduce it. Closing this out since I didn't see similar reports following this, but will come back if there's something identifiable
