### ISSUE TITLE
Sending notification to user on task completion

### ISSUE THREAD

**Issue by Harshitg** [dchevell/flask-executor#8]
I am new to flask-executor and have not implemented any distributed python function prior to this. flask-executor seems simple to implement and should meet the requirements for my flask application. The context of the implementation is as follows:

I have created financial risk management application, whereby the user can run certain time consuming statistical functions after entering a specific calculation date. These functions take 4-5 minutes in certain cases to execute and follow the process of reading data from MSSQL db >> doing the calculation >> storing the results back to db >> querying the results >> re-directing to a page with results. The way I currently have it coded, the server performs the function, then once it has finished, it returns the results page, so the user is stuck at a loading screen for up to 4-5 minutes.

The help i am seeking is to find an example where once the results are stored to the database, the URL from where the function was executed should notify of the task completion and then re-direct the users to the results page?

In addition i keep getting "NameError: name 'executor' is not defined".

Thanks

**Comment by dchevell** [comment]
Hey @Harshitg !

What you want to do is totally possible, but it requires a bit of javascript.

Basically, you want to do something like this:

1. Create an API endpoint that runs your calculation.It should use `executor.submit_stored` ([docs](https://flask-executor.readthedocs.io/en/latest/api/flask_executor.html#flask_executor.executor.Executor.submit_stored)) to store the `Future` that will contain the results of your calculation job. You need to figure out a `future_key` that's unique to your logged in user, so you can refer back to it later without conflicting with other users' calculations.
2. Create an API endpoint that returns the results of your `Future`. It should use `executor.futures` to query the status of your task if it's still running, or return the result when it's done.
The docs provide a simple example of this: 
```
@app.route('/start-task')
def start_task():
    executor.submit_stored('calc_power', pow, 323, 1235)
    return jsonify({'result':'success'})

@app.route('/get-result')
def get_result():
    if not executor.futures.done('calc_power'):
        future_status = executor.futures._state('calc_power')
        return jsonify({'status': future_status})
    future = executor.futures.pop('calc_power')
    return jsonify({'status': done, 'result': future.result()})
```
3. Set up your user interface so that instead of just submitting a form that loads a new page to calculate your function, it uses javascript to post your calculation date to your first API endpoint
4. Set up your web app with a periodic javascript function  that polls your second API endpoint for the status of your running task every 5-10 seconds. When your task is done, this function should show something in the UI that makes the results visible to you.


As you can see most of the work here is actually writing javascript to submit your task without taking the user away from their page, then polling for the results of your task to bring them back into the page when they're ready. There are lots of ways you can go about this, but I hope this gives you some ideas about what you can do!

**Comment by Harshitg** [comment]
Thanks Dave, i will try and use the worksteps and report with an example so others can use. In the meantime, i am facing a unusual issue working on Python 3.7, whereby the following error is received upon requesting to run the function:

`NameError: name 'executor' is not defined
`

The setup and configuration as required in under the [documentation](https://flask-executor.readthedocs.io/en/latest/index.html#configuration) exists.

**Comment by dchevell** [comment]
Hey @Harshitg, I can't reproduce this. Your error sounds as you're using a variable in a context where it hasn't been defined yet. Can you provide any example  code from your project that shows how you're  initialising the executor, and how you're submitting tasks?

**Comment by Harshitg** [comment]
Thanks, here is the example:

```
from flask_executor import Executor

def slow_function():
     This function would do the calculation and store the output into the DB


```
```
    @expose('/trade',methods=['GET','POST'])
    def tradevaluation(self):
        dat,strip= [],[]
        counter = db.session.query(Trade).all()
        for row in counter:
            cpn=db.session.query(Trade).filter_by(id=row.id).first()
            val_date_mn=date_format(cpn.trade_date)
            dat.append(cpn.trade_date)
            strip.append(cpn.stripid)

        #some_object = 'This is a test'
        executor.submit(slow_function)
        #return 'hello'
        result_tradeoff=db.session.query(Offset).filter(Offset.trade__offset_id.in_(strip),Offset.valtype=='trade')
        result_tradeval=db.session.query(Valuation).filter(Valuation.trade_id.in_(strip),Valuation.val_date.in_(dat))
        results = zip(list(result_tradeoff),list(result_tradeval))

        return self.render_template('valuation_results.html', results=results,
                                title_a = 'Calculations', title_b = 'Hedge Management',
                                        title_c = 'Trade Date Designation Results')
```

the config.py files has 

######## Flask executor config ############
```
EXECUTOR_TYPE = 'thread'
EXECUTOR_MAX_WORKERS = 10
```

**Comment by dchevell** [comment]
Hey @Harshitg, at what point in the code are you initialising the executor? e.g.:

```
app = Flask(__name__)

executor = Executor(app)
```

**Comment by Harshitg** [comment]
There you go:

```
app = Flask(__name__)
app.config.from_object('config')
db = SQLA(app)
executor = Executor(app)
```

**Comment by dchevell** [comment]
Hey @Harshitg,

Are you doing this in the same file or are you importing the executor object somewhere? Based on the errors you've provided so far this doesn't look like a Flask-Executor problem, it seems as though you're trying to use the `executor` object in a place where it hasn't been defined or imported.
